/**
 * Generate the e2e fixtures fresh per run (run via `tsx e2e/gen-env.ts`):
 *
 *   - a TRUSTED ES256 keypair (the allow-listed issuer the patched n8n trusts),
 *   - a SECOND, non-allow-listed ES256 keypair (scenario 6: validly signed, wrong issuer), and
 *   - a TRUSTED RS256 keypair whose PUBLIC key IS in the mock JWKS (scenario 5 unpinned-alg:
 *     a token whose signature verifies but whose alg is not in the pinned ES256 allow-list,
 *     so the rejection is attributable specifically to algorithm pinning — not to a JWKS miss).
 *
 * Outputs (all gitignored — zero key bytes committed):
 *   - e2e/mock-jwks/jwks.json   public JWK(s), bind-mounted into the mock JWKS server
 *   - e2e/.generated.env        env_file feeding the n8n container (iss/aud/jwks/...)
 *   - e2e/.generated-keys.json  PRIVATE JWKs, read in-process by the host driver
 *
 * iss/aud/jwksUri come ONLY from e2e/constants.ts, so the driver and the container
 * cannot drift.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { exportJWK, generateKeyPair, type JWK } from 'jose';

import {
  GENERATED_ENV_PATH,
  JWKS_OUTPUT_PATH,
  MOCK_JWKS_URL,
  TEST_ALGORITHM,
  TEST_AUDIENCE,
  TEST_ISSUER,
  UNPINNED_ALGORITHM,
} from './constants.js';

const KEYS_OUTPUT_PATH = 'e2e/.generated-keys.json';

export interface GeneratedKeys {
  /** Trusted issuer signing key (private JWK + kid). */
  trusted: { kid: string; privateJwk: JWK };
  /** Non-allow-listed issuer signing key (private JWK + kid). */
  rogue: { kid: string; privateJwk: JWK };
  /** Trusted-issuer RS256 key whose public half IS published in the mock JWKS. */
  unpinnedAlg: { kid: string; privateJwk: JWK };
}

async function makeKeypair(
  kid: string,
  alg: string,
): Promise<{ kid: string; publicJwk: JWK; privateJwk: JWK }> {
  const { privateKey, publicKey } = await generateKeyPair(alg, { extractable: true });
  const publicJwk = await exportJWK(publicKey);
  publicJwk.kid = kid;
  publicJwk.alg = alg;
  publicJwk.use = 'sig';
  const privateJwk = await exportJWK(privateKey);
  privateJwk.kid = kid;
  privateJwk.alg = alg;
  return { kid, publicJwk, privateJwk };
}

function repoRoot(): string {
  // This file lives at <root>/e2e/gen-env.ts.
  return resolve(dirname(fileURLToPath(import.meta.url)), '..');
}

function writeFile(relativePath: string, contents: string): string {
  const abs = resolve(repoRoot(), relativePath);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, contents, 'utf8');
  return abs;
}

async function main(): Promise<void> {
  const trusted = await makeKeypair('e2e-trusted', TEST_ALGORITHM);
  const rogue = await makeKeypair('e2e-rogue', TEST_ALGORITHM);
  const unpinnedAlg = await makeKeypair('e2e-unpinned-alg', UNPINNED_ALGORITHM);

  // Mock JWKS serves the trusted ES256 key AND the RS256 key used by the unpinned-alg
  // case (so its signature verifies — the rejection must come from the pinned-alg list,
  // not a JWKS miss). The rogue key is intentionally absent so a rogue-signed token cannot
  // verify even if its issuer were allow-listed.
  const jwks = { keys: [trusted.publicJwk, unpinnedAlg.publicJwk] };
  const jwksPath = writeFile(JWKS_OUTPUT_PATH, `${JSON.stringify(jwks, null, 2)}\n`);

  const env = [
    '# GENERATED by e2e/gen-env.ts — do not edit, do not commit.',
    `N8N_PROXY_AUTH_JWKS_URL=${MOCK_JWKS_URL}`,
    `N8N_PROXY_AUTH_ISSUER=${TEST_ISSUER}`,
    `N8N_PROXY_AUTH_AUDIENCE=${TEST_AUDIENCE}`,
    `N8N_PROXY_AUTH_ALGORITHMS=${TEST_ALGORITHM}`,
    'N8N_SECURE_COOKIE=false',
    '',
  ].join('\n');
  const envPath = writeFile(GENERATED_ENV_PATH, env);

  const keys: GeneratedKeys = {
    trusted: { kid: trusted.kid, privateJwk: trusted.privateJwk },
    rogue: { kid: rogue.kid, privateJwk: rogue.privateJwk },
    unpinnedAlg: { kid: unpinnedAlg.kid, privateJwk: unpinnedAlg.privateJwk },
  };
  const keysPath = writeFile(KEYS_OUTPUT_PATH, `${JSON.stringify(keys, null, 2)}\n`);

  console.log(
    `[gen-env] wrote ${jwksPath}\n[gen-env] wrote ${envPath}\n[gen-env] wrote ${keysPath}`,
  );
}

void main();
